name: Approve Label Workflow # Name of the workflow

on:
  pull_request: # Trigger the workflow when an issue event occurs
    types: [labeled] # Only when a label is added to an issue

jobs:
  approve_job: # Name of the job
    if: ${{ github.event.label.name == 'dev approved' }} # Run the job only if the label added is 'approve'
    runs-on: ubuntu-latest # Operating system to run the job on
    steps:
      - name: Checkout code # Name of the step
        uses: actions/checkout@v2 # Action to checkout the code
      - name: Run tests # Name of the step
        run: echo "Running tests..." # Command to run the tests
      - name: Deploy # Name of the step
        uses: some-action/deploy@v1 # Action to deploy the code
        with:
          environment: dev # Environment to deploy the code to
  
  #deploy_dev:
  #  #if: contains(github.event.pull_request.labels.*.name, 'dev approved')
  #  needs: [terraform-plan]
  #  uses: ./.github/workflows/apply-workflow.yml
  #  with:
  #    path: tfplan
  #    gh_environment: dev
  #    #tf_version: 1.3.0
  #  secrets:
  #    DEV_DEPLOY_ROLE: ${{ secrets.DEV_DEPLOY_ROLE }}

